name: on-pr
on:
    pull_request:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: npm ci
            - run: npx nx affected --target=lint --parallel=3
            - run: npx nx affected --target=test --parallel=3 --configuration=ci
            - run: npx nx affected --target=build --parallel=3 --exclude=web
